version: '3.8'
services:
  postgres:
    build: .
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgadmpass
    volumes:
      - ./pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
  minio:
    build:
      context: .
      dockerfile: minio.Dockerfile
    entrypoint: "/bin/bash -c 'mkdir -p /backup/pgbackrest && /usr/bin/minio server /backup --console-address :9001'"
    restart: always
    user: root
    environment:
      - MINIO_ROOT_USER=miniouser
      - MINIO_ROOT_PASSWORD=miniopass
    volumes:
      - ./minio-pgbackup:/backup
    ports:
      - "9000:9000"
      - "9001:9001"
