version: '3.8'
services:
  postgres:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PG_POSTGRES_PASSWORD=pgadmpass
      - PG_ENCRYPTION_KEY=dce48283c5ea92664bb4ad1ca31bde26
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./initdb.sql:/etc/postgresql/initdb.sql
    ports:
      - 5432:5432
